/**
 * Generates src/components/command-center/map-data.ts: pre-projected SVG
 * paths for Africa + GCC (and grey context around them) from Natural Earth
 * 1:110m via world-atlas. Run with: pnpm map:build. Output is committed.
 */
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { geoMercator, geoPath } from "d3-geo";
import { feature } from "topojson-client";
import type { Feature, FeatureCollection, Geometry } from "geojson";

const require = createRequire(import.meta.url);
const topo = require("world-atlas/countries-110m.json");

// ISO 3166 numeric -> alpha-2 for the countries we plot.
const FOCUS: Record<string, string> = {
  "012": "DZ", "024": "AO", "204": "BJ", "072": "BW", "854": "BF", "108": "BI", "132": "CV", "120": "CM",
  "140": "CF", "148": "TD", "174": "KM", "178": "CG", "180": "CD", "384": "CI", "262": "DJ", "818": "EG",
  "226": "GQ", "232": "ER", "748": "SZ", "231": "ET", "266": "GA", "270": "GM", "288": "GH", "324": "GN",
  "624": "GW", "404": "KE", "426": "LS", "430": "LR", "434": "LY", "450": "MG", "454": "MW", "466": "ML",
  "478": "MR", "480": "MU", "504": "MA", "508": "MZ", "516": "NA", "562": "NE", "566": "NG", "646": "RW",
  "678": "ST", "686": "SN", "690": "SC", "694": "SL", "706": "SO", "710": "ZA", "728": "SS", "729": "SD",
  "834": "TZ", "768": "TG", "788": "TN", "800": "UG", "894": "ZM", "716": "ZW", "732": "EH",
  "784": "AE", "682": "SA", "634": "QA", "414": "KW", "048": "BH", "512": "OM",
};
// Neighbours drawn as context only.
const CONTEXT = new Set(["887", "368", "364", "400", "376", "760", "422", "275", "792", "724", "620", "380", "300", "196", "250"]);

// Fallback centroids (lon, lat) for countries too small to appear at 1:110m.
const FALLBACK: Record<string, [number, number]> = {
  BH: [50.55, 26.07], MU: [57.55, -20.3], CV: [-23.6, 15.1], KM: [43.3, -11.7], ST: [6.6, 0.25],
  SC: [55.45, -4.6], QA: [51.2, 25.3], GM: [-15.4, 13.45],
};

const all = feature(topo, topo.objects.countries) as unknown as FeatureCollection<Geometry, { name: string }>;
const focus = all.features.filter((f) => FOCUS[String(f.id)]);
const context = all.features.filter((f) => CONTEXT.has(String(f.id)));

const W = 560;
const H = 600;
const projection = geoMercator().fitExtent([[8, 8], [W - 8, H - 8]], { type: "FeatureCollection", features: focus } as FeatureCollection);
const path = geoPath(projection);
const round = (d: string | null) => (d ?? "").replace(/(\d+\.\d{1})\d+/g, "$1");

const countries = focus.map((f: Feature<Geometry, { name: string }>) => {
  const code = FOCUS[String(f.id)];
  const [cx, cy] = path.centroid(f);
  return { code, d: round(path(f)), cx: +cx.toFixed(1), cy: +cy.toFixed(1) };
});
const present = new Set(countries.map((c) => c.code));
for (const [code, lonlat] of Object.entries(FALLBACK)) {
  if (present.has(code)) continue;
  const [x, y] = projection(lonlat)!;
  countries.push({ code, d: "", cx: +x.toFixed(1), cy: +y.toFixed(1) });
}
const ctx = context.map((f) => round(path(f))).filter(Boolean);

const out = `// Generated by scripts/build-map.ts from Natural Earth 1:110m (public domain). Do not edit.
export const MAP_VIEWBOX = "0 0 ${W} ${H}";
export const MAP_COUNTRIES: { code: string; d: string; cx: number; cy: number }[] = ${JSON.stringify(countries)};
export const MAP_CONTEXT: string[] = ${JSON.stringify(ctx)};
`;
writeFileSync("src/components/command-center/map-data.ts", out);
console.log(`map-data.ts: ${countries.length} countries, ${ctx.length} context shapes, ${(out.length / 1024).toFixed(0)} KB`);
